### PR TITLE
Update stats constructor in tests

### PR DESCRIPTION
**Pull request by tmigot**
There is also the following error in `dummy_solver`:
```
┌ Error: caught exception
│   e =
│    MethodError: no method matching adjoint(::SuiteSparse.SPQR.QRSparse{Float64, Int64})
│    Closest candidates are:
│      adjoint(::Union{QR, LinearAlgebra.QRCompactWY, QRPivoted}) at julia\stdlib\v1.8\LinearAlgebra\src\qr.jl:517
│      adjoint(::Union{Cholesky, CholeskyPivoted}) at julia\stdlib\v1.8\LinearAlgebra\src\cholesky.jl:558
│      adjoint(::SuiteSparse.CHOLMOD.Factor) at julia\stdlib\v1.8\SuiteSparse\src\cholmod.jl:340
│      ...
└ @ SolverBenchmark SolverBenchmark.jl\src\run_solver.jl:155
```

### CODE REVIEW

**Comment by dpo** [comment]
> There is also the following error in dummy_solver:

dummy_solver assumes that J is dense. Maybe that has changed?

Also, have to run the docs manually to find the error in the log files.

**Comment by tmigot** [comment]
The issue with the documentation came from a new release of Plots.jl https://github.com/JuliaSmoothOptimizers/BenchmarkProfiles.jl/issues/89

**Comment by dpo** [comment]
> Since, some update of ADNLPModels the matrix is now sparse... Maybe we should move with this issue [JuliaSmoothOptimizers/SolverCore.jl#36](https://github.com/JuliaSmoothOptimizers/SolverCore.jl/issues/36) to avoid maintaining various `dummy_solver` everywhere?

Sure.

**Comment by tmigot** [comment]
@dpo I added the `SolverCore.dummy_solver`, so that no error messages appear in the tests.

**Review by dpo — APPROVED** [review]

**Pull request merged**
