### PR TITLE
format tables with PrettyTables

### PR DESCRIPTION
**Pull request by dpo**
- output text tables in any format supported by PrettyTables
- use PrettyTables for LaTeX output
- predefine two highlighters
- simplify tests

### CODE REVIEW

**Comment by dpo** [comment]
With these changes, we can do things such as:

1) automatically highlight failures (even if we don't show the status column)
[Screen Shot 2020-06-04 at 16.24.31.pdf](https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/files/4767809/Screen.Shot.2020-06-04.at.16.24.31.pdf)

2) highlight stats using a color gradient based on one of the measures (e.g., time)
[Screen Shot 2020-06-04 at 16.22.05.pdf](https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/files/4767816/Screen.Shot.2020-06-04.at.16.22.05.pdf)

**Comment by abelsiqueira** [comment]
This is great, thanks. Only the docs need to be updated, otherwise I think it's good to go.

**Comment by dpo** [comment]
Finally! I never found a way to prevent Documenter from complaining about methods that aren't even exported.

It's expected that coverage went down as I deprecated a few methods that are still in there for now.

**Comment by abelsiqueira** [comment]
Thanks

**Comment by amontoison** [comment]
If you want to prevent Documenter from complaining about methods that aren't even exported, you only need that https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/master/docs/make.jl#L5.

**Comment by dpo** [comment]
Doesn't work unfortunately.

**Comment by amontoison** [comment]
If it doesn't work it's because the methods are still exported. #61

**Pull request merged**
