### PR TITLE
Bump to BenchmarkProfiles 0.3.4

### PR DESCRIPTION
**Pull request by tmigot**
The last release of `BenchmarkProfiles.jl` added a backend in the `performance_profile.jl`. Following, what was already documented here, I used the `PlotsBackend`.

We also have to convert the data into `Float64` to satisfy a constraint on the input matrix [see L.129 in BenchmarkProfiles.jl](https://github.com/JuliaSmoothOptimizers/BenchmarkProfiles.jl/blob/446c63bfa87fe04ac5c1d1d98e8736f75be43ba9/src/performance_profiles.jl#L129).

### CODE REVIEW

**Review by dpo — APPROVED** [review]

**Comment by abelsiqueira** [comment]
Looks like there is still some issue with the docs. @tmigot, do you know what it is?

**Comment by tmigot** [comment]
> Looks like there is still some issue with the docs. @tmigot, do you know what it is?

Same problem as with BenchmarkProfiles.jl, I had to set the environment variable. There is a new error with the nightly now, but it is unrelated.

**Comment by abelsiqueira** [comment]
Thanks. Does this need a new release?

**Comment by tmigot** [comment]
@abelsiqueira Yes, it does for compatibility with BenchmarkProfiles.

**Pull request merged**
