### PR TITLE
improve pkgbenchmark tools

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Errored [here](https://travis-ci.org/github/JuliaSmoothOptimizers/SolverBenchmark.jl/jobs/707858616#L724), though it's not obvious why to me.

**Comment by dpo** [comment]
The tests pass locally, and on CirrusCI, they fail at a different place. Are those tests not run sequentially?

**Comment by abelsiqueira** [comment]
Should be. Could PkgBenchmark be doing something threaded?

**Comment by abelsiqueira** [comment]
Passed locally for me as well.

**Comment by dpo** [comment]
I understand the error now. Because the benchmark suite is still defined differently on `master`, the stats resulting from the benchmarks on `master` don't have the keys I check for here. So it's normal that it fails.

What I don't understand is how tests pass on Windows...

**Comment by dpo** [comment]
The Appveyor build was succeeding because it doesn't have the `CI` environment variable. I added it, and now it fails (as it should). I have to merge this and we'll see in subsequent PRs how it's working out.

**Pull request merged**
