### PR TITLE
profile judgement results

### PR DESCRIPTION
**Pull request by dpo**
Profile master vs a commit or a pull request (checked out locally) in a given package. Example:
```julia
julia> using PkgBenchmark
julia> commit = benchmarkpkg("Krylov")  # current state of repository
julia> master = benchmarkpkg("Krylov", "master")
julia> judgement = judge(commit, master)
julia> using SolverBenchmark
julia> p = profile_package(judgement)
```

Result:

judgement

### CODE REVIEW

**Comment by amontoison** [comment]
it's a useful feature!
Is it normal that we don't have any plot for `memory` and `allocations` benchmark?

**Comment by dpo** [comment]
That seems to be an artefact of the profiles when those measures are identical:
```julia
julia> stats = judgement_results_to_dataframes(judgement)
Dict{Symbol,DataFrames.DataFrame} with 2 entries:
  :baseline => 13×5 DataFrames.DataFrame…
  :target   => 13×5 DataFrames.DataFrame…

julia> stats[:baseline]
13×5 DataFrames.DataFrame
│ Row │ name          │ time      │ memory    │ gctime   │ allocations │
│     │ String        │ Float64   │ Float64   │ Float64  │ Int64       │
├─────┼───────────────┼───────────┼───────────┼──────────┼─────────────┤
│ 1   │ DivGrad N=128 │ 8.83141e9 │ 5.03407e7 │ 721614.0 │ 18          │
│ 2   │ DivGrad N=32  │ 1.79443e7 │ 789200.0  │ 0.0      │ 18          │
│ 3   │ DivGrad N=64  │ 3.63403e8 │ 6.2963e6  │ 0.0      │ 17          │
│ 4   │ LF10          │ 2820.0    │ 1536.0    │ 0.0      │ 11          │
│ 5   │ LFAT5         │ 2319.1    │ 1104.0    │ 0.0      │ 10          │
│ 6   │ bcsstk01      │ 18572.0   │ 3040.0    │ 0.0      │ 12          │
│ 7   │ bcsstk02      │ 111460.0  │ 3280.0    │ 0.0      │ 12          │
│ 8   │ bcsstm02      │ 2905.11   │ 2400.0    │ 0.0      │ 10          │
│ 9   │ ex5           │ 8350.67   │ 1872.0    │ 0.0      │ 11          │
│ 10  │ mesh1e1       │ 5017.5    │ 2160.0    │ 0.0      │ 10          │
│ 11  │ mesh1em1      │ 9307.0    │ 2496.0    │ 0.0      │ 11          │
│ 12  │ mesh1em6      │ 5152.6    │ 2160.0    │ 0.0      │ 10          │
│ 13  │ nos4          │ 45084.0   │ 5184.0    │ 0.0      │ 13          │

julia> stats[:target]
13×5 DataFrames.DataFrame
│ Row │ name          │ time      │ memory    │ gctime   │ allocations │
│     │ String        │ Float64   │ Float64   │ Float64  │ Int64       │
├─────┼───────────────┼───────────┼───────────┼──────────┼─────────────┤
│ 1   │ DivGrad N=128 │ 9.46305e9 │ 5.03407e7 │ 733637.0 │ 18          │
│ 2   │ DivGrad N=32  │ 1.77131e7 │ 789200.0  │ 0.0      │ 18          │
│ 3   │ DivGrad N=64  │ 3.54296e8 │ 6.2963e6  │ 0.0      │ 17          │
│ 4   │ LF10          │ 2821.56   │ 1536.0    │ 0.0      │ 11          │
│ 5   │ LFAT5         │ 1977.6    │ 1104.0    │ 0.0      │ 10          │
│ 6   │ bcsstk01      │ 18413.0   │ 3040.0    │ 0.0      │ 12          │
│ 7   │ bcsstk02      │ 111725.0  │ 3280.0    │ 0.0      │ 12          │
│ 8   │ bcsstm02      │ 2984.78   │ 2400.0    │ 0.0      │ 10          │
│ 9   │ ex5           │ 8424.67   │ 1872.0    │ 0.0      │ 11          │
│ 10  │ mesh1e1       │ 4921.67   │ 2160.0    │ 0.0      │ 10          │
│ 11  │ mesh1em1      │ 8754.0    │ 2496.0    │ 0.0      │ 11          │
│ 12  │ mesh1em6      │ 4952.8    │ 2160.0    │ 0.0      │ 10          │
│ 13  │ nos4          │ 45033.0   │ 5184.0    │ 0.0      │ 13          │
```

**Comment by abelsiqueira** [comment]
This is great, thanks.

PS. nice branch name.

**Comment by dpo** [comment]
I thought you would notice ;-).

**Pull request merged**
