### PR TITLE
Only change branches during pkgmark tests on CI

### PR DESCRIPTION
**Pull request by abelsiqueira**
The problem is that it erases the current changes, so testing before commit means you lose your work.

### CODE REVIEW

**Comment by dpo** [comment]
Doesn't PkgBenchmark return an error if you have uncommitted changes?

**Comment by abelsiqueira** [comment]
Didn't for me. I had some changes and lost them.

**Comment by dpo** [comment]
Ok. This doesn't seem ideal but I don't know how else to prevent that situation. I'm sorry you lost some changes. When I try to run this kind of judgement locally, PkgBenchmark complains when my branch is dirty. Maybe as a test, the behavior is different...

**Comment by abelsiqueira** [comment]
Yes, it's only when `pkg> test`ing. If I do it using `include` it returns an error.

**Comment by dpo** [comment]
Seems like a bug to me.

**Pull request merged**
