### PR TITLE
Fix colors

### PR DESCRIPTION
**Pull request by dpo**
@amontoison 

Example: https://gist.github.com/dpo/a2e6a0ae884219057e1c9b139fc8f46a

### CODE REVIEW

**Comment by dpo** [comment]
The only issue here is `doc/Project.toml`, which is fixed in #38.

**Comment by amontoison** [comment]
Thanks! I will use it for my benchmarks.

**Comment by dpo** [comment]
I think we can go ahead and merge. The build will succeed because of #38.

**Comment by abelsiqueira** [comment]
Done. Thanks.

**Comment by dpo** [comment]
Thank you.

**Pull request merged**
